// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalMarblesNameDao is internal type for wrapping internal DAO implements.
type internalMarblesNameDao = *internal.MarblesNameDao

// marblesNameDao is the data access object for table marbles_name.
// You can define custom methods on it to extend its functionality as you wish.
type marblesNameDao struct {
	internalMarblesNameDao
}

var (
	// MarblesName is globally public accessible object for table marbles_name operations.
	MarblesName = marblesNameDao{
		internal.NewMarblesNameDao(),
	}
)

// Fill with you ideas below.
