// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalMarblesDao is internal type for wrapping internal DAO implements.
type internalMarblesDao = *internal.MarblesDao

// marblesDao is the data access object for table marbles.
// You can define custom methods on it to extend its functionality as you wish.
type marblesDao struct {
	internalMarblesDao
}

var (
	// Marbles is globally public accessible object for table marbles operations.
	Marbles = marblesDao{
		internal.NewMarblesDao(),
	}
)

// Fill with you ideas below.
