// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MarblesNameDao is the data access object for table marbles_name.
type MarblesNameDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns MarblesNameColumns // columns contains all the column names of Table for convenient usage.
}

// MarblesNameColumns defines and stores column names for table marbles_name.
type MarblesNameColumns struct {
	Id         string //
	TenantId   string //
	Name       string //
	PictureUrl string //
}

// marblesNameColumns holds the columns for table marbles_name.
var marblesNameColumns = MarblesNameColumns{
	Id:         "id",
	TenantId:   "tenant_id",
	Name:       "name",
	PictureUrl: "picture_url",
}

// NewMarblesNameDao creates and returns a new DAO object for table data access.
func NewMarblesNameDao() *MarblesNameDao {
	return &MarblesNameDao{
		group:   "default",
		table:   "marbles_name",
		columns: marblesNameColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MarblesNameDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MarblesNameDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MarblesNameDao) Columns() MarblesNameColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MarblesNameDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MarblesNameDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx).Hook(TenantHook)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MarblesNameDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
